### ISSUE TITLE
Add version number to plugin settings menu

### ISSUE THREAD

**Issue by jsmorabito** [eharris128/Obsidian-LLM-Plugin#117]
[Plugin settings menu main screen - LLM Obsidian Plugin (Figma)](https://www.figma.com/file/HdZizHaYKCLPStXprYslxT/LLM-Obsidian-Plugin?type=design&node-id=2674-377&mode=design&t=ckM2xdGG5Ky9oC37-4)

# Requirements

1. Add a version number of the plugin to the bottom of the plugin signature group (highlighted by the red box in the design)
   1. Version number must update with each release

**Comment by eharris128** [comment]
Resolved. https://github.com/r-mahoney/Obsidian-LLM-Plugin/releases/tag/0.17.1
